Add disclaimer about mutiple sway sessions
alebastr/sway-systemd pull request #12
Opened 2022-01-10 22:36 UTC by markstos

I had started a second Sway session to debug why my first sway session was freezing, but then some other things broke.

Maybe this is so rare that it's not worth mentioning that it's not supported, but it seems worth documenting *somewhere*.

2022-01-10 22:45 UTC, Scrumplex requested changes
I don't think it's as uncommon as you think. You can also run Sway nested inside your currently running Sway session. That would also lead to the same issue.

2022-01-10 22:45 UTC, Scrumplex commented on README.md
> + - Supporting multiple concurrent sway sessions for the same user. It's uncommon and doing so would cause problems for which there are no easy solutions: To make this work, we set `WAYLAND_DISPLAY` w
> To make this work, we set `WAYLAND_DISPLAY` with a `systemd --user` sesssion.

typo here ("sesssion")

2022-01-10 22:45 UTC, Scrumplex commented on README.md
> + - Supporting multiple concurrent sway sessions for the same user. It's uncommon and doing so would cause problems for which there are no easy solutions: To make this work, we set `WAYLAND_DISPLAY` w
> `systemd --user` session

nit: maybe just call it "systemd user session"

2022-01-10 22:45 UTC, Scrumplex commented on README.md
> + - Supporting multiple concurrent sway sessions for the same user. It's uncommon and doing so would cause problems for which there are no easy solutions: To make this work, we set `WAYLAND_DISPLAY` w
> If the user starts a second Sway instance on the same machine

nit: "on the same machine" doesn't sound right IMO

2022-01-10 22:46 UTC, markstos commented
You are welcome to take idea and modify the text as you see fit.  

Good comment about possibly nested sessions!

2022-01-10 22:49 UTC, markstos commented
Maybe there's a way to check to see if the user attempts to use this tool with a second session and throw an error or print a warning if so? 

That would have helped me debug my problems today. I guess it was useful that I could still run a second Sway session, and I didn't really need any background systemd services to work there. So the behavior I would have liked would have been for the tool to notice that a Sway session had already been set up with systemd, and then just print a warning and not further modify the environment.

2022-01-10 22:54 UTC, Scrumplex commented
It could be as simple as checking if `WAYLAND_DISPLAY" is present in the output of `systemctl --user show-environment`. This would also keep us from overriding it if other WMs or DEs set the variable (For example if the user is running Sway nested inside some other wayland compositor).

2022-01-11 06:02 UTC, alebastr commented
> It could be as simple as checking if `WAYLAND_DISPLAY` is present in the output of `systemctl --user show-environment`. This would also keep us from overriding it if other WMs or DEs set the variable (For example if the user is running Sway nested inside some other wayland compositor).

`WAYLAND_DISPLAY` or `DISPLAY`. Sway can be nested inside of an X session and the same problem would appear.
One problem is that it requires making `--with-cleanup` behavior default. I was apprehensive of that as waiting for `swaymsg -t subscribe '["shutdown"]'` looks fragile, but enough time has passed and nobody reported any issues caused by this.

Overall I agree both with the disclaimer and with the script change. This week is quite busy though, so I don't know when I'll have enough time to implement and test it :disappointed:

2022-01-11 18:07 UTC, markstos commented
Another option is to set an additional variable, like `SWAY_SYSTEMD_ACTIVE=1`. This would be cleaned up when sway exists. 

If that variable exists, warn and exit.

2022-01-21 05:56 UTC, merged